version: "3.8"
services:
  db:
    container_name: postgres_container
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql:Z

  keycloak:
    command: start-dev --import-realm --http-relative-path=/auth
    depends_on:
      - db
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: keycloak
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    image: quay.io/keycloak/keycloak:20.0
    ports:
      - '8080:8080'
    volumes:
      - ./config/realm.json:/opt/keycloak/data/import/realm.json:Z

  pgadmin:
    container_name: pgadmin4_container
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    image: dpage/pgadmin4:6.17
    ports:
      - '8081:80'
    restart: always
    volumes:
      - ./config/pg_servers.json:/pgadmin4/servers.json:Z


volumes:
  db-data:
