version: '3.8'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tdp_dev_db
      POSTGRES_USER: tdp_user
      POSTGRES_PASSWORD: tdp_password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: db
        DB_DATABASE: keycloak
        DB_USER: tdp_user
        DB_SCHEMA: public
        DB_PASSWORD: tdp_password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      ports:
        - 8080:8080
      depends_on:
        - db

  keycloak_config:
    image: quay.io/keycloak/keycloak:legacy
    entrypoint: bash /entrypoint.sh
    environment:
      KC_ADDRESS: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    volumes:
      - ./configure-keycloak.sh:/entrypoint.sh
    depends_on:
      - keycloak

volumes:
  db-data:
  pgadmin-data:
